name: publish sdk and update docs

on:
  pull_request:
    types:
      - closed
    paths:
      - packages/sdk-ethers-v5/src/**
      - packages/sdk-ethers-v5/site/**
      - packages/sdk-ethers-v5/package.json
      - packages/sdk-ethers-v5/tsconfig.json
      - packages/sdk-ethers-v5/tsconfig.*.json
      - packages/sdk-ethers-v6/src/**
      - packages/sdk-ethers-v6/site/**
      - packages/sdk-ethers-v6/package.json
      - packages/sdk-ethers-v6/tsconfig.json
      - packages/sdk-ethers-v6/tsconfig.*.json
      - packages/sdk-viem/src/**
      - packages/sdk-viem/site/**
      - packages/sdk-viem/package.json
      - packages/sdk-viem/tsconfig.json
      - packages/sdk-viem/tsconfig.*.json
      - .github/workflows/publish.yml
  
permissions:
  contents: write
  packages: write

jobs:
  publish:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Checkout our working repository
    - name: Conventional Changelog Action
      id: changelog
      uses: chromatic-protocol/conventional-changelog-action@v5.2.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: false
        pre-release: true
        git-push: true
        skip-on-empty: false
        version-file: packages/sdk-viem/package.json,packages/sdk-ethers-v5/package.json,packages/sdk-ethers-v6/package.json
        skip-tag: true
        git-message: 'chore(release): sdk@{version}'
        # skip-version-file: false
        # skip-commit: false
    - uses: actions/setup-node@v4
      id: setup-node
      with:
        node-version: 18.15
        cache: yarn
        registry-url: https://registry.npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_CHROMATIC }}    
    
    # publish package to npm
    - name: build and publish
      run: |
        yarn install
        yarn workspaces run build
        yarn workspaces run pub --network-timeout 600000

    # export markdown docs to docs repository
    - uses: chromatic-protocol/action-github-app-token@v2
      id: generate-token
      with:
        app_id: ${{ secrets.PR_ACTION_APP_ID }}
        private_key: ${{ secrets.PR_ACTION_PRIVATE }}
    - uses: actions/checkout@v4
      with:
        repository: chromatic-protocol/docs
        ref: main
        path: docs-repo
        token: ${{ steps.generate-token.outputs.token }}
    - name: export docs:sdk and cp
      run: |
        yarn workspaces run docs:sdk
        # update sdk-viem docs
        cp docs-repo/docs/sdk/reference/sdk-viem/_category_.yml packages/sdk-viem/site/docs/sdk/ 
        rm -rf docs-repo/docs/sdk/reference/sdk-viem/*
        cp -r packages/sdk-viem/site/docs/sdk/* docs-repo/docs/sdk/reference/sdk-viem/
        # update sdk-ethers-v5 docs
        cp docs-repo/docs/sdk/reference/sdk-ethers-v5/_category_.yml packages/sdk-ethers-v5/site/docs/sdk/ 
        rm -rf docs-repo/docs/sdk/reference/sdk-ethers-v5/*
        cp -r packages/sdk-ethers-v5/site/docs/sdk/* docs-repo/docs/sdk/reference/sdk-ethers-v5/
        cp packages/sdk-ethers-v5/src/gen/deployedAddress.ts docs-repo/docs/contracts/reference/
        # update sdk-ethers-v6 docs
        cp docs-repo/docs/sdk/reference/sdk-ethers-v6/_category_.yml packages/sdk-ethers-v6/site/docs/sdk/ 
        rm -rf docs-repo/docs/sdk/reference/sdk-ethers-v6/*
        cp -r packages/sdk-ethers-v6/site/docs/sdk/* docs-repo/docs/sdk/reference/sdk-ethers-v6/
        cp packages/sdk-ethers-v6/src/gen/deployedAddress.ts docs-repo/docs/contracts/reference/

    - name: pull-request
      uses: peter-evans/create-pull-request@v6
      with:
        base: main
        branch: docs/sdk
        path: docs-repo
        add-paths: |
          docs/sdk/reference/sdk-viem/**
          docs/sdk/reference/sdk-ethers-v5/**
          docs/sdk/reference/sdk-ethers-v6/**
          docs/contracts/reference/deployedAddress.ts
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: ${{ github.event.pull_request.title }}
        title: Changes from sdk
