name: publish sdk-viem

on:
  pull_request:
    types:
      - closed
    paths:
      - packages/sdk-viem/src/**
      - packages/sdk-viem/site/**
      - packages/sdk-viem/package.json
      - packages/sdk-viem/tsconfig.json
      - packages/sdk-viem/tsconfig.*.json
      - .github/workflows/publish-viem.yml
  
permissions:
  contents: write
  packages: write

jobs:
  publish-viem:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Checkout our working repository
    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        output-file: false
        pre-release: true
        git-push: true
        skip-on-empty: false
        version-file: packages/sdk-viem/package.json
        skip-tag: true
        # skip-version-file: false
        # skip-commit: false
    - uses: actions/setup-node@v3
      id: setup-node
      with:
        node-version: 18.15
        cache: yarn
        registry-url: https://registry.npmjs.org
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_CHROMATIC }}    
    
    # TODO publish docs
    - name: build and publish
      working-directory: ./packages/sdk-viem 
      run: |
        yarn install
        yarn build
        yarn publish --access public

    # export markdown docs to docs repository
    - uses: chromatic-protocol/action-github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.PR_ACTION_APP_ID }}
        private_key: ${{ secrets.PR_ACTION_PRIVATE }}
    - uses: actions/checkout@v3
      with:
        repository: chromatic-protocol/docs
        ref: main
        path: packages/sdk-viem/docs-repo
        token: ${{ steps.generate-token.outputs.token }}
    - name: export docs:sdk and cp
      working-directory: ./packages/sdk-viem
      run: |
        yarn docs:sdk
        cp docs-repo/docs/sdk/reference/sdk-viem/_category_.yml site/docs/sdk/ 
        rm -rf docs-repo/docs/sdk/reference/sdk-viem/*
        cp -r site/docs/sdk/* docs-repo/docs/sdk/reference/sdk-viem/
    - name: pull-request
      uses: peter-evans/create-pull-request@v5
      with:
        base: main
        branch: docs/sdk-viem
        path: packages/sdk-viem/docs-repo
        add-paths: |
          docs/sdk/reference/sdk-viem/**
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: ${{ github.event.pull_request.title }}
